{{- if and .Values.secrets.create (not (coalesce .Values.existingSecret .Values.secrets.existingSecret)) .Values.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siftgate.secretName" . }}
  labels:
    {{- include "siftgate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
