import type { CatalogProvider, CatalogPricing } from './catalog.types';

const LAST_UPDATED = '2026-05-03';

function pricing(
  input: number,
  output: number,
  notes?: string,
): CatalogPricing {
  return {
    input,
    output,
    unit: 'usd_per_1m_tokens',
    source: 'builtin-static-placeholder',
    last_updated: LAST_UPDATED,
    manual_review_required: true,
    ...(notes ? { notes } : {}),
  };
}

function provider(
  providerConfig: Omit<CatalogProvider, 'source' | 'overridden'>,
): CatalogProvider {
  return {
    ...providerConfig,
    source: 'builtin',
    overridden: false,
    models: providerConfig.models.map((model) => ({
      ...model,
      provider: providerConfig.id,
      source: 'builtin',
      overridden: false,
    })),
  };
}

export const BUILTIN_PROVIDER_CATALOG: CatalogProvider[] = [
  provider({
    id: 'openai',
    name: 'OpenAI',
    base_url: 'https://api.openai.com',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      responses: '/v1/responses',
      embeddings: '/v1/embeddings',
      image: '/v1/images/generations',
      audio: '/v1/audio/transcriptions',
      realtime: '/v1/realtime',
    },
    model_prefixes: ['gpt', 'o', 'text-embedding', 'dall-e'],
    capabilities: ['structured_output', 'streaming', 'tools'],
    models: [
      {
        id: 'gpt-4o',
        provider: 'openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses' },
        capabilities: ['structured_output', 'streaming', 'tools'],
        limits: { max_context_tokens: 128000 },
        pricing: pricing(2.5, 10),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-4o-mini',
        provider: 'openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses' },
        capabilities: ['structured_output', 'streaming', 'tools'],
        limits: { max_context_tokens: 128000 },
        pricing: pricing(0.15, 0.6),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'text-embedding-3-small',
        provider: 'openai',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        limits: { dimensions: [512, 1536] },
        pricing: pricing(0.02, 0),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-image-1',
        provider: 'openai',
        modalities: ['image'],
        endpoints: { image: '/v1/images/generations' },
        capabilities: ['image_generation'],
        pricing: pricing(5, 0, 'Image pricing varies by size and quality.'),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-4o-realtime-preview',
        provider: 'openai',
        modalities: ['text', 'audio', 'realtime'],
        endpoints: { realtime: '/v1/realtime' },
        capabilities: ['realtime', 'streaming'],
        pricing: pricing(5, 20, 'Realtime pricing varies by input/output modality.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'anthropic',
    name: 'Anthropic',
    base_url: 'https://api.anthropic.com',
    auth_type: 'x-api-key',
    endpoints: { messages: '/v1/messages' },
    model_prefixes: ['claude'],
    capabilities: ['streaming', 'tools', 'vision'],
    models: [
      {
        id: 'claude-sonnet-4-20250514',
        provider: 'anthropic',
        modalities: ['text', 'vision'],
        endpoints: { messages: '/v1/messages' },
        capabilities: ['streaming', 'tools', 'vision'],
        limits: { max_context_tokens: 200000 },
        pricing: pricing(3, 15),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'claude-haiku-4-20250514',
        provider: 'anthropic',
        modalities: ['text', 'vision'],
        endpoints: { messages: '/v1/messages' },
        capabilities: ['streaming', 'tools', 'vision'],
        limits: { max_context_tokens: 200000 },
        pricing: pricing(0.8, 4),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'google',
    name: 'Google Gemini / Vertex',
    base_url: 'https://generativelanguage.googleapis.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1beta/openai/chat/completions', embeddings: '/v1beta/openai/embeddings' },
    model_prefixes: ['gemini'],
    capabilities: ['vision', 'long_context'],
    models: [
      {
        id: 'gemini-2.5-pro',
        provider: 'google',
        modalities: ['text', 'vision', 'audio', 'video'],
        endpoints: { chat_completions: '/v1beta/openai/chat/completions' },
        capabilities: ['vision', 'long_context'],
        limits: { max_context_tokens: 1000000 },
        pricing: pricing(1.25, 10),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'text-embedding-004',
        provider: 'google',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1beta/openai/embeddings' },
        capabilities: ['embeddings'],
        pricing: pricing(0.01, 0),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'azure-openai',
    name: 'Azure OpenAI',
    base_url: 'https://{resource}.openai.azure.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/openai/deployments/{deployment}/chat/completions', embeddings: '/openai/deployments/{deployment}/embeddings' },
    model_prefixes: ['gpt', 'text-embedding'],
    capabilities: ['structured_output', 'streaming'],
    models: [
      {
        id: 'gpt-4o',
        provider: 'azure-openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/openai/deployments/{deployment}/chat/completions' },
        capabilities: ['structured_output', 'streaming'],
        pricing: pricing(2.5, 10, 'Azure pricing depends on region and deployment.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'openrouter',
    name: 'OpenRouter',
    base_url: 'https://openrouter.ai/api',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['openai', 'anthropic', 'google', 'meta-llama', 'mistralai'],
    capabilities: ['openai_compatible', 'multi_provider'],
    models: [
      {
        id: 'openai/gpt-4o-mini',
        provider: 'openrouter',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['openai_compatible'],
        pricing: pricing(0.15, 0.6, 'OpenRouter pricing may include router-specific markups.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'groq',
    name: 'Groq',
    base_url: 'https://api.groq.com/openai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['llama', 'mixtral', 'gemma'],
    capabilities: ['openai_compatible', 'low_latency'],
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        provider: 'groq',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'low_latency'],
        pricing: pricing(0.59, 0.79),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'mistral',
    name: 'Mistral AI',
    base_url: 'https://api.mistral.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['mistral', 'codestral', 'pixtral'],
    capabilities: ['openai_compatible', 'vision'],
    models: [
      {
        id: 'mistral-large-latest',
        provider: 'mistral',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'tools'],
        pricing: pricing(2, 6),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'pixtral-large-latest',
        provider: 'mistral',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['vision'],
        pricing: pricing(2, 6),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'deepseek',
    name: 'DeepSeek',
    base_url: 'https://api.deepseek.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['deepseek'],
    capabilities: ['openai_compatible', 'reasoning'],
    models: [
      {
        id: 'deepseek-chat',
        provider: 'deepseek',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.27, 1.1),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'deepseek-reasoner',
        provider: 'deepseek',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['reasoning'],
        pricing: pricing(0.55, 2.19),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'xai',
    name: 'xAI',
    base_url: 'https://api.x.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['grok'],
    capabilities: ['openai_compatible', 'vision'],
    models: [
      {
        id: 'grok-3',
        provider: 'xai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'vision'],
        pricing: pricing(3, 15),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'cohere',
    name: 'Cohere',
    base_url: 'https://api.cohere.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v2/chat', rerank: '/v2/rerank', embeddings: '/v2/embed' },
    model_prefixes: ['command', 'embed', 'rerank'],
    capabilities: ['rerank', 'embeddings'],
    models: [
      {
        id: 'command-r-plus',
        provider: 'cohere',
        modalities: ['text'],
        endpoints: { chat_completions: '/v2/chat' },
        capabilities: ['streaming', 'tools'],
        pricing: pricing(2.5, 10),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'rerank-v3.5',
        provider: 'cohere',
        modalities: ['text', 'rerank'],
        endpoints: { rerank: '/v2/rerank' },
        capabilities: ['rerank'],
        pricing: pricing(0.01, 0, 'Rerank pricing is often request-based; verify manually.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'voyage',
    name: 'Voyage AI',
    base_url: 'https://api.voyageai.com',
    auth_type: 'bearer',
    endpoints: { embeddings: '/v1/embeddings', rerank: '/v1/rerank' },
    model_prefixes: ['voyage', 'rerank'],
    capabilities: ['embeddings', 'rerank'],
    models: [
      {
        id: 'voyage-3-large',
        provider: 'voyage',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        limits: { dimensions: [256, 512, 1024, 2048] },
        pricing: pricing(0.18, 0),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'jina',
    name: 'Jina AI',
    base_url: 'https://api.jina.ai',
    auth_type: 'bearer',
    endpoints: { embeddings: '/v1/embeddings', rerank: '/v1/rerank' },
    model_prefixes: ['jina'],
    capabilities: ['embeddings', 'rerank'],
    models: [
      {
        id: 'jina-embeddings-v3',
        provider: 'jina',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        pricing: pricing(0.02, 0),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'together',
    name: 'Together AI',
    base_url: 'https://api.together.xyz',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['meta-llama', 'mistralai', 'Qwen'],
    capabilities: ['openai_compatible', 'open_weights'],
    models: [
      {
        id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
        provider: 'together',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.88, 0.88),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'fireworks',
    name: 'Fireworks AI',
    base_url: 'https://api.fireworks.ai/inference',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['accounts/fireworks/models', 'llama'],
    capabilities: ['openai_compatible', 'open_weights'],
    models: [
      {
        id: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
        provider: 'fireworks',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.9, 0.9),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'ollama',
    name: 'Ollama',
    base_url: 'http://localhost:11434',
    auth_type: 'none',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['llama', 'qwen', 'mistral', 'gemma'],
    capabilities: ['local', 'openai_compatible'],
    models: [
      {
        id: 'llama3.1',
        provider: 'ollama',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['local'],
        pricing: pricing(0, 0, 'Local model; hardware cost is not included.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'vllm',
    name: 'vLLM',
    base_url: 'http://localhost:8000',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['local', 'llama', 'qwen', 'mistral'],
    capabilities: ['local', 'openai_compatible'],
    models: [
      {
        id: 'local-model',
        provider: 'vllm',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['local', 'streaming'],
        pricing: pricing(0, 0, 'Local model; hardware cost is not included.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'openai-compatible',
    name: 'OpenAI-compatible custom',
    base_url: 'https://your-provider.example',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses', embeddings: '/v1/embeddings' },
    model_prefixes: [],
    capabilities: ['openai_compatible', 'custom'],
    models: [
      {
        id: 'custom-model',
        provider: 'openai-compatible',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['custom'],
        pricing: pricing(0, 0, 'Replace with provider-specific pricing.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
];
