import type { CatalogProvider, CatalogPricing } from './catalog.types';
import { inferCatalogCompatibilityProfiles } from './compatibility-profiles';

const LAST_UPDATED = '2026-05-05';
const STALE_AFTER_DAYS = 90;

function pricing(
  input: number,
  output: number,
  notes?: string,
  overrides: Partial<CatalogPricing> = {},
): CatalogPricing {
  return {
    input,
    output,
    currency: 'USD',
    unit: 'usd_per_1m_tokens',
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      ...overrides.units,
    },
    source: 'builtin-reference',
    source_url: 'https://github.com/seanbabalala/ai-gateway/blob/main/docs/PROVIDER_CATALOG.md',
    last_updated: LAST_UPDATED,
    manual_review_required: true,
    stale_after_days: STALE_AFTER_DAYS,
    pricing_confidence: 'low',
    ...(notes ? { notes } : {}),
    ...overrides,
  };
}

function promptCachingPricing(
  input: number,
  output: number,
  cacheReadInput: number,
  cacheCreationInput: number,
  notes?: string,
): CatalogPricing {
  return pricing(input, output, notes, {
    cache_read_input: cacheReadInput,
    cache_creation_input: cacheCreationInput,
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      cache_read_input: 'usd_per_1m_cache_read_input_tokens',
      cache_creation_input: 'usd_per_1m_cache_write_input_tokens',
    },
  });
}

function referencePricing(
  sourceUrl: string,
  notes: string,
  overrides: Partial<CatalogPricing> = {},
): CatalogPricing {
  return {
    currency: overrides.currency || 'USD',
    unit: overrides.unit || 'review_required',
    units: overrides.units,
    source: overrides.source || 'provider-reference',
    source_url: sourceUrl,
    last_updated: overrides.last_updated || LAST_UPDATED,
    manual_review_required: true,
    stale_after_days: overrides.stale_after_days || STALE_AFTER_DAYS,
    pricing_confidence: overrides.pricing_confidence || 'low',
    notes,
    ...overrides,
  };
}

function embeddingPricing(input: number, notes?: string): CatalogPricing {
  return pricing(input, 0, notes, {
    embedding: input,
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      embedding: 'usd_per_1m_embedding_tokens',
    },
  });
}

function imagePricing(input: number, notes?: string): CatalogPricing {
  return pricing(input, 0, notes, {
    image: input,
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      image: 'usd_per_image_or_token_equivalent',
    },
  });
}

function audioPricing(input: number, output = 0, notes?: string): CatalogPricing {
  return pricing(input, output, notes, {
    audio: input,
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      audio: 'usd_per_audio_minute_or_token_equivalent',
    },
  });
}

function rerankPricing(input: number, notes?: string): CatalogPricing {
  return pricing(input, 0, notes, {
    rerank: input,
    units: {
      input: 'usd_per_1m_input_tokens',
      output: 'usd_per_1m_output_tokens',
      rerank: 'usd_per_1k_rerank_requests_or_token_equivalent',
    },
  });
}

function provider(
  providerConfig: Omit<CatalogProvider, 'source' | 'overridden'>,
): CatalogProvider {
  const providerPricing = providerConfig.pricing
    ? { ...providerConfig.pricing }
    : providerConfig.models.find((model) => model.pricing)?.pricing;
  return {
    ...providerConfig,
    pricing: providerPricing ? { ...providerPricing } : undefined,
    compatibility_profiles:
      providerConfig.compatibility_profiles ||
      inferCatalogCompatibilityProfiles(providerConfig as CatalogProvider),
    source: 'builtin',
    overridden: false,
    models: providerConfig.models.map((model) => ({
      ...model,
      provider: providerConfig.id,
      source: 'builtin',
      overridden: false,
    })),
  };
}

export const BUILTIN_PROVIDER_CATALOG: CatalogProvider[] = [
  provider({
    id: 'openai',
    name: 'OpenAI',
    base_url: 'https://api.openai.com',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      responses: '/v1/responses',
      embeddings: '/v1/embeddings',
      image: '/v1/images/generations',
      audio: '/v1/audio/transcriptions',
      realtime: '/v1/realtime',
    },
    model_prefixes: ['gpt', 'o', 'text-embedding', 'dall-e'],
    capabilities: ['structured_output', 'streaming', 'tools', 'prompt_cache', 'read_cache'],
    prompt_cache: true,
    read_cache: true,
    models: [
      {
        id: 'gpt-4o',
        provider: 'openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses' },
        capabilities: ['structured_output', 'streaming', 'tools', 'prompt_cache', 'read_cache'],
        limits: { max_context_tokens: 128000 },
        pricing: promptCachingPricing(2.5, 10, 1.25, 2.5),
        prompt_cache: true,
        read_cache: true,
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-4o-mini',
        provider: 'openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses' },
        capabilities: ['structured_output', 'streaming', 'tools', 'prompt_cache', 'read_cache'],
        limits: { max_context_tokens: 128000 },
        pricing: promptCachingPricing(0.15, 0.6, 0.075, 0.15),
        prompt_cache: true,
        read_cache: true,
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'text-embedding-3-small',
        provider: 'openai',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        limits: { dimensions: [512, 1536] },
        pricing: embeddingPricing(0.02),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-image-1',
        provider: 'openai',
        modalities: ['image'],
        endpoints: { image: '/v1/images/generations' },
        capabilities: ['image_generation'],
        pricing: imagePricing(5, 'Image pricing varies by size and quality.'),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'gpt-4o-realtime-preview',
        provider: 'openai',
        modalities: ['text', 'audio', 'realtime'],
        endpoints: { realtime: '/v1/realtime' },
        capabilities: ['realtime', 'streaming'],
        pricing: audioPricing(5, 20, 'Realtime pricing varies by input/output modality.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'anthropic',
    name: 'Anthropic',
    base_url: 'https://api.anthropic.com',
    auth_type: 'x-api-key',
    endpoints: { messages: '/v1/messages' },
    model_prefixes: ['claude'],
    capabilities: ['streaming', 'tools', 'vision', 'prompt_cache', 'read_cache', 'write_cache'],
    prompt_cache: true,
    read_cache: true,
    write_cache: true,
    models: [
      {
        id: 'claude-sonnet-4-20250514',
        provider: 'anthropic',
        modalities: ['text', 'vision'],
        endpoints: { messages: '/v1/messages' },
        capabilities: ['streaming', 'tools', 'vision', 'prompt_cache', 'read_cache', 'write_cache'],
        limits: { max_context_tokens: 200000 },
        pricing: promptCachingPricing(3, 15, 0.3, 3.75),
        prompt_cache: true,
        read_cache: true,
        write_cache: true,
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'claude-haiku-4-20250514',
        provider: 'anthropic',
        modalities: ['text', 'vision'],
        endpoints: { messages: '/v1/messages' },
        capabilities: ['streaming', 'tools', 'vision', 'prompt_cache', 'read_cache', 'write_cache'],
        limits: { max_context_tokens: 200000 },
        pricing: promptCachingPricing(0.8, 4, 0.08, 1),
        prompt_cache: true,
        read_cache: true,
        write_cache: true,
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'google',
    name: 'Google Gemini / Vertex',
    base_url: 'https://generativelanguage.googleapis.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1beta/openai/chat/completions', embeddings: '/v1beta/openai/embeddings' },
    model_prefixes: ['gemini'],
    capabilities: ['vision', 'long_context'],
    models: [
      {
        id: 'gemini-2.5-pro',
        provider: 'google',
        modalities: ['text', 'vision', 'audio', 'video'],
        endpoints: { chat_completions: '/v1beta/openai/chat/completions' },
        capabilities: ['vision', 'long_context'],
        limits: { max_context_tokens: 1000000 },
        pricing: pricing(1.25, 10),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'text-embedding-004',
        provider: 'google',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1beta/openai/embeddings' },
        capabilities: ['embeddings'],
        pricing: embeddingPricing(0.01),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'azure-openai',
    name: 'Azure OpenAI',
    base_url: 'https://{resource}.openai.azure.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/openai/deployments/{deployment}/chat/completions', embeddings: '/openai/deployments/{deployment}/embeddings' },
    model_prefixes: ['gpt', 'text-embedding'],
    capabilities: ['structured_output', 'streaming'],
    models: [
      {
        id: 'gpt-4o',
        provider: 'azure-openai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/openai/deployments/{deployment}/chat/completions' },
        capabilities: ['structured_output', 'streaming'],
        pricing: pricing(2.5, 10, 'Azure pricing depends on region and deployment.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'openrouter',
    name: 'OpenRouter',
    base_url: 'https://openrouter.ai/api',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['openai', 'anthropic', 'google', 'meta-llama', 'mistralai'],
    capabilities: ['openai_compatible', 'multi_provider'],
    models: [
      {
        id: 'openai/gpt-4o-mini',
        provider: 'openrouter',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['openai_compatible'],
        pricing: pricing(0.15, 0.6, 'OpenRouter pricing may include router-specific markups.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'groq',
    name: 'Groq',
    base_url: 'https://api.groq.com/openai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['llama', 'mixtral', 'gemma'],
    capabilities: ['openai_compatible', 'low_latency'],
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        provider: 'groq',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'low_latency'],
        pricing: pricing(0.59, 0.79),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'mistral',
    name: 'Mistral AI',
    base_url: 'https://api.mistral.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['mistral', 'codestral', 'pixtral'],
    capabilities: ['openai_compatible', 'vision'],
    models: [
      {
        id: 'mistral-large-latest',
        provider: 'mistral',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'tools'],
        pricing: pricing(2, 6),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'pixtral-large-latest',
        provider: 'mistral',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['vision'],
        pricing: pricing(2, 6),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'deepseek',
    name: 'DeepSeek',
    base_url: 'https://api.deepseek.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['deepseek'],
    capabilities: ['openai_compatible', 'reasoning'],
    models: [
      {
        id: 'deepseek-chat',
        provider: 'deepseek',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.27, 1.1),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'deepseek-reasoner',
        provider: 'deepseek',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['reasoning'],
        pricing: pricing(0.55, 2.19),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'xai',
    name: 'xAI',
    base_url: 'https://api.x.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['grok'],
    capabilities: ['openai_compatible', 'vision'],
    models: [
      {
        id: 'grok-3',
        provider: 'xai',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'vision'],
        pricing: pricing(3, 15),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'cohere',
    name: 'Cohere',
    base_url: 'https://api.cohere.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v2/chat', rerank: '/v2/rerank', embeddings: '/v2/embed' },
    model_prefixes: ['command', 'embed', 'rerank'],
    capabilities: ['rerank', 'embeddings'],
    models: [
      {
        id: 'command-r-plus',
        provider: 'cohere',
        modalities: ['text'],
        endpoints: { chat_completions: '/v2/chat' },
        capabilities: ['streaming', 'tools'],
        pricing: pricing(2.5, 10),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'rerank-v3.5',
        provider: 'cohere',
        modalities: ['text', 'rerank'],
        endpoints: { rerank: '/v2/rerank' },
        capabilities: ['rerank'],
        pricing: rerankPricing(0.01, 'Rerank pricing is often request-based; verify manually.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'voyage',
    name: 'Voyage AI',
    base_url: 'https://api.voyageai.com',
    auth_type: 'bearer',
    endpoints: { embeddings: '/v1/embeddings', rerank: '/v1/rerank' },
    model_prefixes: ['voyage', 'rerank'],
    capabilities: ['embeddings', 'rerank'],
    models: [
      {
        id: 'voyage-3-large',
        provider: 'voyage',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        limits: { dimensions: [256, 512, 1024, 2048] },
        pricing: embeddingPricing(0.18),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'jina',
    name: 'Jina AI',
    base_url: 'https://api.jina.ai',
    auth_type: 'bearer',
    endpoints: { embeddings: '/v1/embeddings', rerank: '/v1/rerank' },
    model_prefixes: ['jina'],
    capabilities: ['embeddings', 'rerank'],
    models: [
      {
        id: 'jina-embeddings-v3',
        provider: 'jina',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        pricing: embeddingPricing(0.02),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'together',
    name: 'Together AI',
    base_url: 'https://api.together.xyz',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['meta-llama', 'mistralai', 'Qwen'],
    capabilities: ['openai_compatible', 'open_weights'],
    models: [
      {
        id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
        provider: 'together',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.88, 0.88),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'fireworks',
    name: 'Fireworks AI',
    base_url: 'https://api.fireworks.ai/inference',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['accounts/fireworks/models', 'llama'],
    capabilities: ['openai_compatible', 'open_weights'],
    models: [
      {
        id: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
        provider: 'fireworks',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming'],
        pricing: pricing(0.9, 0.9),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'ollama',
    name: 'Ollama',
    base_url: 'http://localhost:11434',
    auth_type: 'none',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['llama', 'qwen', 'mistral', 'gemma'],
    capabilities: ['local', 'openai_compatible'],
    models: [
      {
        id: 'llama3.1',
        provider: 'ollama',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['local'],
        pricing: pricing(0, 0, 'Local model; hardware cost is not included.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'vllm',
    name: 'vLLM',
    base_url: 'http://localhost:8000',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', embeddings: '/v1/embeddings' },
    model_prefixes: ['local', 'llama', 'qwen', 'mistral'],
    capabilities: ['local', 'openai_compatible'],
    models: [
      {
        id: 'local-model',
        provider: 'vllm',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['local', 'streaming'],
        pricing: pricing(0, 0, 'Local model; hardware cost is not included.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    base_url: 'https://bedrock-runtime.{region}.amazonaws.com',
    auth_type: 'none',
    endpoints: {
      chat_completions: '/model/{modelId}/converse',
      embeddings: '/model/{modelId}/invoke',
      image: '/model/{modelId}/invoke',
    },
    model_prefixes: ['amazon.', 'anthropic.', 'cohere.', 'meta.', 'mistral.', 'us.amazon.', 'us.anthropic.'],
    capabilities: ['managed_models', 'sigv4_required', 'region_pricing'],
    pricing: referencePricing(
      'https://aws.amazon.com/bedrock/pricing/',
      'Bedrock pricing varies by region, model provider, provisioned throughput, and inference profile. Configure verified local prices before cost routing.',
    ),
    models: [
      {
        id: 'us.amazon.nova-pro-v1:0',
        provider: 'aws-bedrock',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/model/us.amazon.nova-pro-v1:0/converse' },
        capabilities: ['managed_models', 'vision'],
        pricing: referencePricing(
          'https://aws.amazon.com/bedrock/pricing/',
          'Amazon Nova rates are region and throughput dependent.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
        provider: 'aws-bedrock',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/model/anthropic.claude-3-5-sonnet-20241022-v2:0/converse' },
        capabilities: ['managed_models', 'vision', 'tools'],
        pricing: referencePricing(
          'https://aws.amazon.com/bedrock/pricing/',
          'Anthropic Bedrock pricing should be checked against the target AWS region.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'amazon.titan-embed-text-v2:0',
        provider: 'aws-bedrock',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/model/amazon.titan-embed-text-v2:0/invoke' },
        capabilities: ['embeddings'],
        pricing: referencePricing(
          'https://aws.amazon.com/bedrock/pricing/',
          'Titan embedding prices vary by region.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'alibaba-qwen',
    name: 'Alibaba Qwen / Tongyi',
    base_url: 'https://dashscope.aliyuncs.com/compatible-mode',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
      image: '/v1/images/generations',
      audio: '/v1/audio/transcriptions',
      video: '/v1/videos/generations',
    },
    model_prefixes: ['qwen', 'qwq', 'qvq', 'text-embedding', 'wan'],
    capabilities: ['openai_compatible', 'vision', 'multilingual', 'china_region'],
    pricing: referencePricing(
      'https://www.alibabacloud.com/help/en/model-studio/billing-for-model-studio',
      'DashScope prices vary by region, model family, and international/China billing plan.',
    ),
    models: [
      {
        id: 'qwen-plus',
        provider: 'alibaba-qwen',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'tools', 'structured_output'],
        pricing: referencePricing(
          'https://www.alibabacloud.com/help/en/model-studio/qwen-api',
          'Qwen chat aliases should be reviewed against Model Studio model/version docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'qwen-turbo',
        provider: 'alibaba-qwen',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'fast'],
        pricing: referencePricing(
          'https://www.alibabacloud.com/help/en/model-studio/qwen-api',
          'Qwen Turbo rates are docs-review references.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'qwen-vl-max',
        provider: 'alibaba-qwen',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['vision'],
        pricing: referencePricing(
          'https://www.alibabacloud.com/help/en/model-studio/qwen-vl-api',
          'Qwen-VL model availability and prices require local review.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'text-embedding-v4',
        provider: 'alibaba-qwen',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        pricing: referencePricing(
          'https://www.alibabacloud.com/help/en/model-studio/text-embedding-synchronous-api',
          'Embedding prices vary by model and region.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'wan2.5-t2v-preview',
        provider: 'alibaba-qwen',
        modalities: ['video'],
        endpoints: { video: '/v1/videos/generations' },
        capabilities: ['video_generation'],
        pricing: referencePricing(
          'https://www.alibabacloud.com/help/en/model-studio/wan-video-generation',
          'Wan video generation is treated as async preview metadata in SiftGate.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'baidu-qianfan',
    name: 'Baidu Qianfan / Wenxin',
    base_url: 'https://qianfan.baidubce.com',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v2/chat/completions',
      embeddings: '/v2/embeddings',
      image: '/v2/images/generations',
    },
    model_prefixes: ['ernie', 'wenxin', 'bge'],
    capabilities: ['multilingual', 'china_region', 'openai_compatible'],
    pricing: referencePricing(
      'https://cloud.baidu.com/doc/qianfan-docs/s/Jm8r1826a',
      'Baidu Qianfan pricing depends on model, region, account plan, and token unit. Review locally before cost routing.',
    ),
    models: [
      {
        id: 'ernie-4.5-turbo-128k',
        provider: 'baidu-qianfan',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v2/chat/completions' },
        capabilities: ['streaming', 'long_context', 'vision'],
        limits: { max_context_tokens: 128000 },
        pricing: referencePricing(
          'https://cloud.baidu.com/doc/qianfan-docs/s/7m95lyy43',
          'ERNIE model names and token prices should be checked against Qianfan docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'ernie-x1-turbo-32k',
        provider: 'baidu-qianfan',
        modalities: ['text'],
        endpoints: { chat_completions: '/v2/chat/completions' },
        capabilities: ['reasoning', 'streaming'],
        limits: { max_context_tokens: 32000 },
        pricing: referencePricing(
          'https://cloud.baidu.com/doc/qianfan-docs/s/7m95lyy43',
          'ERNIE X1 pricing is a docs-review reference.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'volcengine-ark',
    name: 'Volcengine Ark / Doubao',
    base_url: 'https://ark.cn-beijing.volces.com/api',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v3/chat/completions',
      embeddings: '/v3/embeddings',
      image: '/v3/images/generations',
      audio: '/v3/audio/transcriptions',
      video: '/v3/videos/generations',
    },
    model_prefixes: ['doubao', 'ep-'],
    capabilities: ['openai_compatible', 'multimodal', 'china_region'],
    pricing: referencePricing(
      'https://www.volcengine.com/docs/82379/1949118',
      'Volcengine Ark model prices are deployment and endpoint dependent; operators should pin endpoint IDs and verified rates.',
    ),
    models: [
      {
        id: 'doubao-seed-1-6',
        provider: 'volcengine-ark',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v3/chat/completions' },
        capabilities: ['streaming', 'tools', 'vision'],
        pricing: referencePricing(
          'https://www.volcengine.com/docs/82379/1624284',
          'Doubao model catalog should be reviewed for exact endpoint IDs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'doubao-embedding-large-text',
        provider: 'volcengine-ark',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v3/embeddings' },
        capabilities: ['embeddings'],
        pricing: referencePricing(
          'https://www.volcengine.com/docs/82379/1099522',
          'Doubao embedding prices are review-required references.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'doubao-seedance-1-0-pro',
        provider: 'volcengine-ark',
        modalities: ['video'],
        endpoints: { video: '/v3/videos/generations' },
        capabilities: ['video_generation'],
        pricing: referencePricing(
          'https://www.volcengine.com/docs/82379/1520757',
          'Seedance video generation is async/provider-specific and should be verified before routing.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'zhipu',
    name: 'Zhipu AI / GLM',
    base_url: 'https://open.bigmodel.cn/api/paas',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v4/chat/completions',
      embeddings: '/v4/embeddings',
      image: '/v4/images/generations',
    },
    model_prefixes: ['glm', 'chatglm', 'embedding', 'cogview'],
    capabilities: ['openai_compatible', 'reasoning', 'vision', 'china_region'],
    pricing: referencePricing(
      'https://docs.bigmodel.cn/cn/guide/models/price',
      'Zhipu pricing is published by model family and should be reviewed for the active account plan.',
    ),
    models: [
      {
        id: 'glm-4.5',
        provider: 'zhipu',
        modalities: ['text'],
        endpoints: { chat_completions: '/v4/chat/completions' },
        capabilities: ['reasoning', 'streaming', 'tools'],
        pricing: referencePricing(
          'https://docs.bigmodel.cn/cn/guide/models/text/glm-4.5',
          'GLM-4.5 pricing is a review-required reference.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'glm-4.5v',
        provider: 'zhipu',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v4/chat/completions' },
        capabilities: ['vision', 'reasoning'],
        pricing: referencePricing(
          'https://docs.bigmodel.cn/cn/guide/models/multimodal/glm-4.5v',
          'GLM vision rates should be reviewed before cost routing.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'embedding-3',
        provider: 'zhipu',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v4/embeddings' },
        capabilities: ['embeddings'],
        pricing: referencePricing(
          'https://docs.bigmodel.cn/cn/guide/models/embedding/embedding-3',
          'Embedding model metadata is review-required.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'moonshot',
    name: 'Moonshot AI / Kimi',
    base_url: 'https://api.moonshot.cn',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['moonshot', 'kimi'],
    capabilities: ['openai_compatible', 'long_context', 'reasoning', 'china_region'],
    pricing: referencePricing(
      'https://platform.moonshot.cn/docs/pricing/chat',
      'Moonshot/Kimi pricing is review-required and varies by model family.',
    ),
    models: [
      {
        id: 'kimi-k2',
        provider: 'moonshot',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'tools', 'long_context'],
        pricing: referencePricing(
          'https://platform.moonshot.cn/docs/guide/use-kimi-k2',
          'Kimi K2 model versioning and prices should be reviewed before production routing.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'moonshot-v1-128k',
        provider: 'moonshot',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['long_context', 'streaming'],
        limits: { max_context_tokens: 128000 },
        pricing: referencePricing(
          'https://platform.moonshot.cn/docs/pricing/chat',
          'Moonshot v1 rates are docs-review references.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'minimax',
    name: 'MiniMax',
    base_url: 'https://api.minimax.io',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/text/chatcompletion_v2',
      audio: '/v1/t2a_v2',
      image: '/v1/image_generation',
      video: '/v1/video_generation',
    },
    model_prefixes: ['MiniMax', 'abab', 'speech', 'hailuo'],
    capabilities: ['multimodal', 'china_region'],
    pricing: referencePricing(
      'https://platform.minimaxi.com/document/price',
      'MiniMax prices vary by API family. Review text, speech, image, and video units separately.',
    ),
    models: [
      {
        id: 'MiniMax-M2',
        provider: 'minimax',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/text/chatcompletion_v2' },
        capabilities: ['streaming', 'tools'],
        pricing: referencePricing(
          'https://platform.minimaxi.com/docs/api-reference/text/chat-completion',
          'MiniMax text model aliases and prices require docs review.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'speech-02-hd',
        provider: 'minimax',
        modalities: ['audio'],
        endpoints: { audio_speech: '/v1/t2a_v2' },
        capabilities: ['speech'],
        pricing: referencePricing(
          'https://platform.minimaxi.com/docs/api-reference/audio/text-to-speech',
          'MiniMax speech pricing is unit-specific and review-required.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'hailuo-02',
        provider: 'minimax',
        modalities: ['video'],
        endpoints: { video: '/v1/video_generation' },
        capabilities: ['video_generation'],
        pricing: referencePricing(
          'https://platform.minimaxi.com/docs/api-reference/video/video-generation',
          'Hailuo video generation is async/provider-specific.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'tencent-hunyuan',
    name: 'Tencent Hunyuan',
    base_url: 'https://api.hunyuan.cloud.tencent.com',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
      image: '/v1/images/generations',
      video: '/v1/videos/generations',
    },
    model_prefixes: ['hunyuan', 'hy-'],
    capabilities: ['openai_compatible', 'multimodal', 'china_region'],
    pricing: referencePricing(
      'https://cloud.tencent.com/document/product/1729/97731',
      'Tencent Hunyuan prices vary by model, region, and API surface.',
    ),
    models: [
      {
        id: 'hunyuan-turbos-latest',
        provider: 'tencent-hunyuan',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'tools'],
        pricing: referencePricing(
          'https://cloud.tencent.com/document/product/1729/111007',
          'Hunyuan text models should be reviewed against Tencent Cloud docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'hunyuan-vision',
        provider: 'tencent-hunyuan',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['vision'],
        pricing: referencePricing(
          'https://cloud.tencent.com/document/product/1729/111007',
          'Hunyuan vision model availability varies by account and region.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'hunyuan-video',
        provider: 'tencent-hunyuan',
        modalities: ['video'],
        endpoints: { video: '/v1/videos/generations' },
        capabilities: ['video_generation'],
        pricing: referencePricing(
          'https://cloud.tencent.com/document/product/1823/130078',
          'Hunyuan video generation is async/provider-specific and review-required.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: '01ai',
    name: '01.AI / Yi',
    base_url: 'https://api.lingyiwanwu.com',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['yi-'],
    capabilities: ['openai_compatible', 'china_region'],
    pricing: referencePricing(
      'https://platform.lingyiwanwu.com/docs',
      '01.AI/Yi public API availability and pricing should be verified by the operator.',
    ),
    models: [
      {
        id: 'yi-lightning',
        provider: '01ai',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'fast'],
        pricing: referencePricing(
          'https://platform.lingyiwanwu.com/docs',
          'Yi model metadata is a review-required reference.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'replicate',
    name: 'Replicate',
    base_url: 'https://api.replicate.com',
    auth_type: 'bearer',
    endpoints: {
      image: '/v1/models/{owner}/{model}/predictions',
      video: '/v1/models/{owner}/{model}/predictions',
      chat_completions: '/v1/models/{owner}/{model}/predictions',
    },
    model_prefixes: ['black-forest-labs/', 'minimax/', 'stability-ai/', 'meta/'],
    capabilities: ['model_marketplace', 'async_predictions', 'manual_adapter_required'],
    pricing: referencePricing(
      'https://replicate.com/pricing',
      'Replicate pricing is model and hardware dependent. SiftGate treats these entries as routing metadata until an operator pins exact model costs.',
    ),
    models: [
      {
        id: 'black-forest-labs/flux-schnell',
        provider: 'replicate',
        modalities: ['image'],
        endpoints: { image: '/v1/models/black-forest-labs/flux-schnell/predictions' },
        capabilities: ['image_generation', 'async_predictions'],
        pricing: referencePricing(
          'https://replicate.com/black-forest-labs/flux-schnell',
          'Replicate model prices are hardware/version dependent.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'minimax/hailuo-02',
        provider: 'replicate',
        modalities: ['video'],
        endpoints: { video: '/v1/models/minimax/hailuo-02/predictions' },
        capabilities: ['video_generation', 'async_predictions'],
        pricing: referencePricing(
          'https://replicate.com/minimax/hailuo-02',
          'Replicate video pricing is model and runtime dependent.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'perplexity',
    name: 'Perplexity',
    base_url: 'https://api.perplexity.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/chat/completions' },
    model_prefixes: ['sonar'],
    capabilities: ['search_grounded', 'openai_compatible'],
    pricing: referencePricing(
      'https://docs.perplexity.ai/guides/pricing',
      'Perplexity prices include model/token and search request components. Review before using cost routing.',
    ),
    models: [
      {
        id: 'sonar',
        provider: 'perplexity',
        modalities: ['text'],
        endpoints: { chat_completions: '/chat/completions' },
        capabilities: ['search_grounded', 'streaming'],
        pricing: referencePricing(
          'https://docs.perplexity.ai/guides/model-cards',
          'Sonar pricing includes search-specific units.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'sonar-pro',
        provider: 'perplexity',
        modalities: ['text'],
        endpoints: { chat_completions: '/chat/completions' },
        capabilities: ['search_grounded', 'streaming'],
        pricing: referencePricing(
          'https://docs.perplexity.ai/guides/pricing',
          'Sonar Pro pricing should be checked against current docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    base_url: 'https://integrate.api.nvidia.com',
    auth_type: 'bearer',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
      rerank: '/v1/ranking',
    },
    model_prefixes: ['nvidia/', 'meta/', 'mistralai/', 'qwen/'],
    capabilities: ['openai_compatible', 'hosted_inference', 'rerank', 'embedding'],
    pricing: referencePricing(
      'https://docs.nvidia.com/nim/large-language-models/latest/pricing.html',
      'NVIDIA NIM pricing depends on hosted API plan or self-hosted infrastructure.',
    ),
    models: [
      {
        id: 'meta/llama-3.1-70b-instruct',
        provider: 'nvidia-nim',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'open_weights'],
        pricing: referencePricing(
          'https://build.nvidia.com/models',
          'NIM hosted model catalog changes frequently; verify exact model IDs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'nvidia/llama-3.2-nv-embedqa-1b-v2',
        provider: 'nvidia-nim',
        modalities: ['text', 'embedding'],
        endpoints: { embeddings: '/v1/embeddings' },
        capabilities: ['embeddings'],
        pricing: referencePricing(
          'https://build.nvidia.com/models',
          'Embedding model prices depend on hosted/self-hosted plan.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'cerebras',
    name: 'Cerebras',
    base_url: 'https://api.cerebras.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['gpt-oss', 'llama', 'qwen'],
    capabilities: ['openai_compatible', 'low_latency'],
    pricing: referencePricing(
      'https://inference-docs.cerebras.ai/support/pricing',
      'Cerebras inference prices and available models should be reviewed before cost routing.',
    ),
    models: [
      {
        id: 'gpt-oss-120b',
        provider: 'cerebras',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'low_latency'],
        pricing: referencePricing(
          'https://inference-docs.cerebras.ai/introduction',
          'Cerebras model availability is docs-review metadata.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'llama3.1-8b',
        provider: 'cerebras',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'low_latency'],
        pricing: referencePricing(
          'https://inference-docs.cerebras.ai/introduction',
          'Cerebras rates should be verified against current pricing docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'sambanova',
    name: 'SambaNova Cloud',
    base_url: 'https://api.sambanova.ai',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions' },
    model_prefixes: ['Meta-Llama', 'Llama', 'DeepSeek', 'Qwen'],
    capabilities: ['openai_compatible', 'open_weights'],
    pricing: referencePricing(
      'https://docs.sambanova.ai/cloud/docs/get-started/pricing',
      'SambaNova Cloud pricing and model availability should be verified by the operator.',
    ),
    models: [
      {
        id: 'Meta-Llama-3.3-70B-Instruct',
        provider: 'sambanova',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['streaming', 'open_weights'],
        pricing: referencePricing(
          'https://docs.sambanova.ai/cloud/docs/capabilities/models',
          'SambaNova model IDs should be reviewed against current model docs.',
        ),
        source: 'builtin',
        overridden: false,
      },
      {
        id: 'Llama-4-Maverick-17B-128E-Instruct',
        provider: 'sambanova',
        modalities: ['text', 'vision'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['vision', 'streaming', 'open_weights'],
        pricing: referencePricing(
          'https://docs.sambanova.ai/cloud/docs/capabilities/models',
          'SambaNova multimodal model support should be verified before production routing.',
        ),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
  provider({
    id: 'openai-compatible',
    name: 'OpenAI-compatible custom',
    base_url: 'https://your-provider.example',
    auth_type: 'bearer',
    endpoints: { chat_completions: '/v1/chat/completions', responses: '/v1/responses', embeddings: '/v1/embeddings' },
    model_prefixes: [],
    capabilities: ['openai_compatible', 'custom'],
    models: [
      {
        id: 'custom-model',
        provider: 'openai-compatible',
        modalities: ['text'],
        endpoints: { chat_completions: '/v1/chat/completions' },
        capabilities: ['custom'],
        pricing: pricing(0, 0, 'Replace with provider-specific pricing.'),
        source: 'builtin',
        overridden: false,
      },
    ],
  }),
];
