import type {
  CatalogEndpoint,
  CatalogModality,
  CatalogPricing,
  CatalogProvider,
} from './provider-catalog.types';

export const PROVIDER_CATALOG_VERSION = '2026-05-03.static.v1';
export const PROVIDER_CATALOG_LAST_UPDATED = '2026-05-03';

const manualTokenPricing = (
  input?: number | null,
  output?: number | null,
  notes?: string,
): CatalogPricing => ({
  input,
  output,
  unit: '1m_tokens',
  currency: 'USD',
  source: 'manual_placeholder',
  last_updated: PROVIDER_CATALOG_LAST_UPDATED,
  manual_review_required: true,
  notes,
});

const operatorPricing = (unit: CatalogPricing['unit'] = 'unknown'): CatalogPricing => ({
  input: null,
  output: null,
  unit,
  currency: 'unknown',
  source: 'operator_required',
  last_updated: PROVIDER_CATALOG_LAST_UPDATED,
  manual_review_required: true,
  notes: 'Local, proxy, marketplace, or deployment pricing must be reviewed by the operator.',
});

const modal = (...values: CatalogModality[]) => values;
const endpoints = (...values: CatalogEndpoint[]) => values;

export const PROVIDER_CATALOG: CatalogProvider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'OpenAI public API across Chat Completions, Responses, embeddings, media, and realtime.',
    base_url: 'https://api.openai.com',
    base_url_matchers: ['api.openai.com'],
    protocols: ['chat_completions', 'responses'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      responses: '/v1/responses',
      embeddings: '/v1/embeddings',
      image_generations: '/v1/images/generations',
      image_edits: '/v1/images/edits',
      audio_transcriptions: '/v1/audio/transcriptions',
      audio_speech: '/v1/audio/speech',
      realtime: '/v1/realtime',
    },
    auth_type: 'bearer',
    key_placeholder: 'sk-...',
    modalities: modal('text', 'vision', 'image', 'audio', 'embedding', 'realtime'),
    capabilities: ['coding', 'reasoning', 'tool_use', 'vision', 'structured_output'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['gpt', 'o', 'text-embedding', 'dall-e', 'tts'],
    tags: ['official', 'openai-compatible'],
    models: [
      {
        id: 'gpt-4.1',
        provider_id: 'openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions', 'responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning', 'tool_use', 'structured_output'],
        limits: { max_context_tokens: 1047576 },
        pricing: manualTokenPricing(2, 8),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gpt-4.1-mini',
        provider_id: 'openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions', 'responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning', 'tool_use', 'structured_output'],
        limits: { max_context_tokens: 1047576 },
        pricing: manualTokenPricing(0.4, 1.6),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gpt-4o',
        provider_id: 'openai',
        modalities: modal('text', 'vision', 'audio'),
        endpoints: endpoints('chat_completions', 'responses'),
        input_types: ['text', 'image', 'audio'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning', 'tool_use', 'structured_output'],
        limits: { max_context_tokens: 128000 },
        pricing: manualTokenPricing(2.5, 10),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gpt-4o-mini',
        provider_id: 'openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions', 'responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['fast', 'coding', 'tool_use', 'structured_output'],
        limits: { max_context_tokens: 128000 },
        pricing: manualTokenPricing(0.15, 0.6),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'o3',
        provider_id: 'openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'coding', 'structured_output'],
        limits: { max_context_tokens: 200000 },
        pricing: manualTokenPricing(2, 8),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'o4-mini',
        provider_id: 'openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'fast', 'structured_output'],
        limits: { max_context_tokens: 200000 },
        pricing: manualTokenPricing(1.1, 4.4),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'text-embedding-3-small',
        provider_id: 'openai',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        limits: { dimensions: [512, 1536] },
        pricing: manualTokenPricing(0.02, 0),
      },
      {
        id: 'text-embedding-3-large',
        provider_id: 'openai',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        limits: { dimensions: [256, 1024, 3072] },
        pricing: manualTokenPricing(0.13, 0),
      },
      {
        id: 'gpt-image-1',
        provider_id: 'openai',
        modalities: modal('image'),
        endpoints: endpoints('image_generations', 'image_edits'),
        input_types: ['text', 'image'],
        output_types: ['image'],
        capabilities: ['image_generation', 'image_edit'],
        pricing: manualTokenPricing(5, 0, 'Placeholder token-equivalent pricing for image workloads.'),
      },
      {
        id: 'dall-e-3',
        provider_id: 'openai',
        modalities: modal('image'),
        endpoints: endpoints('image_generations'),
        input_types: ['text'],
        output_types: ['image'],
        capabilities: ['image_generation'],
        pricing: operatorPricing('image'),
      },
      {
        id: 'gpt-4o-mini-transcribe',
        provider_id: 'openai',
        modalities: modal('audio'),
        endpoints: endpoints('audio_transcriptions'),
        input_types: ['audio', 'file'],
        output_types: ['text'],
        capabilities: ['transcription'],
        pricing: manualTokenPricing(0.6, 0),
      },
      {
        id: 'tts-1',
        provider_id: 'openai',
        modalities: modal('audio'),
        endpoints: endpoints('audio_speech'),
        input_types: ['text'],
        output_types: ['audio'],
        capabilities: ['speech'],
        pricing: manualTokenPricing(15, 0),
      },
      {
        id: 'gpt-4o-realtime-preview',
        provider_id: 'openai',
        modalities: modal('realtime', 'audio', 'text'),
        endpoints: endpoints('realtime'),
        input_types: ['events', 'text', 'audio'],
        output_types: ['events', 'text', 'audio'],
        capabilities: ['realtime'],
        pricing: manualTokenPricing(5, 20),
        supports_realtime: true,
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    base_url: 'https://api.anthropic.com',
    base_url_matchers: ['api.anthropic.com'],
    protocols: ['messages'],
    default_protocol: 'messages',
    endpoints: { messages: '/v1/messages' },
    auth_type: 'x-api-key',
    key_placeholder: 'sk-ant-...',
    modalities: modal('text', 'vision'),
    capabilities: ['coding', 'reasoning', 'analysis', 'vision'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['claude'],
    tags: ['official'],
    models: [
      {
        id: 'claude-opus-4-20250514',
        provider_id: 'anthropic',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('messages'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'coding', 'analysis'],
        limits: { max_context_tokens: 200000 },
        pricing: manualTokenPricing(15, 75),
        supports_streaming: true,
      },
      {
        id: 'claude-sonnet-4-20250514',
        provider_id: 'anthropic',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('messages'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning', 'analysis'],
        limits: { max_context_tokens: 200000 },
        pricing: manualTokenPricing(3, 15),
        supports_streaming: true,
      },
      {
        id: 'claude-3-5-sonnet-latest',
        provider_id: 'anthropic',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('messages'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning', 'analysis'],
        limits: { max_context_tokens: 200000 },
        pricing: manualTokenPricing(3, 15),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    base_url: 'https://generativelanguage.googleapis.com',
    base_url_matchers: ['generativelanguage.googleapis.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1beta/openai/chat/completions',
      embeddings: '/v1beta/openai/embeddings',
      image_generations: '/v1beta/openai/images/generations',
      video_generations: '/v1beta/models/veo:predictLongRunning',
    },
    auth_type: 'bearer',
    key_placeholder: 'AIza...',
    modalities: modal('text', 'vision', 'embedding', 'image', 'video'),
    capabilities: ['multilingual', 'long_context', 'vision', 'coding'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['gemini', 'imagen', 'veo'],
    tags: ['official', 'openai-compatible'],
    models: [
      {
        id: 'gemini-2.5-pro',
        provider_id: 'google-gemini',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image', 'audio', 'video'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'long_context', 'multilingual'],
        limits: { max_context_tokens: 1048576 },
        pricing: manualTokenPricing(null, null),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gemini-2.5-flash',
        provider_id: 'google-gemini',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image', 'audio', 'video'],
        output_types: ['text', 'json'],
        capabilities: ['fast', 'long_context', 'multilingual'],
        limits: { max_context_tokens: 1048576 },
        pricing: manualTokenPricing(null, null),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gemini-embedding-001',
        provider_id: 'google-gemini',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: manualTokenPricing(null, 0),
      },
      {
        id: 'imagen-4.0-generate-preview',
        provider_id: 'google-gemini',
        modalities: modal('image'),
        endpoints: endpoints('image_generations'),
        input_types: ['text', 'image'],
        output_types: ['image'],
        capabilities: ['image_generation'],
        pricing: operatorPricing('image'),
      },
      {
        id: 'veo-3.1-generate-preview',
        provider_id: 'google-gemini',
        modalities: modal('video'),
        endpoints: endpoints('video_generations'),
        input_types: ['text', 'image'],
        output_types: ['video'],
        capabilities: ['video_generation'],
        pricing: operatorPricing('second'),
      },
    ],
  },
  {
    id: 'google-vertex',
    name: 'Google Vertex AI',
    base_url: 'https://LOCATION-aiplatform.googleapis.com',
    base_url_matchers: ['aiplatform.googleapis.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/projects/PROJECT/locations/LOCATION/endpoints/openapi/chat/completions',
      embeddings: '/v1/projects/PROJECT/locations/LOCATION/endpoints/openapi/embeddings',
    },
    auth_type: 'bearer',
    key_placeholder: 'OAuth2 bearer token',
    modalities: modal('text', 'vision', 'embedding', 'image', 'video'),
    capabilities: ['multilingual', 'long_context', 'vision'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['gemini', 'imagen', 'veo'],
    tags: ['official', 'cloud'],
    allows_unknown_models: true,
    models: [
      {
        id: 'gemini-2.5-pro',
        provider_id: 'google-vertex',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image', 'audio', 'video'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'long_context'],
        limits: { max_context_tokens: 1048576 },
        pricing: manualTokenPricing(null, null),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'gemini-embedding-001',
        provider_id: 'google-vertex',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: manualTokenPricing(null, 0),
      },
    ],
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    base_url: 'https://YOUR_RESOURCE.openai.azure.com',
    base_url_matchers: ['openai.azure.com'],
    protocols: ['chat_completions', 'responses'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/openai/deployments/YOUR_DEPLOYMENT/chat/completions?api-version=2024-10-21',
      responses: '/openai/deployments/YOUR_DEPLOYMENT/responses?api-version=2025-04-01-preview',
      embeddings: '/openai/deployments/YOUR_DEPLOYMENT/embeddings?api-version=2024-10-21',
    },
    auth_type: 'api-key-header',
    key_placeholder: 'Azure API key...',
    modalities: modal('text', 'vision', 'embedding', 'image', 'audio'),
    capabilities: ['coding', 'tool_use', 'structured_output'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['gpt', 'o', 'text-embedding'],
    tags: ['cloud', 'deployment-based'],
    allows_unknown_models: true,
    models: [
      {
        id: 'gpt-4o',
        provider_id: 'azure-openai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions', 'responses'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'tool_use', 'structured_output'],
        limits: { max_context_tokens: 128000 },
        pricing: operatorPricing(),
        structured_output: true,
        supports_streaming: true,
      },
      {
        id: 'text-embedding-3-large',
        provider_id: 'azure-openai',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        limits: { dimensions: [256, 1024, 3072] },
        pricing: operatorPricing(),
      },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    base_url: 'https://openrouter.ai',
    base_url_matchers: ['openrouter.ai'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: { chat_completions: '/api/v1/chat/completions' },
    auth_type: 'bearer',
    key_placeholder: 'sk-or-...',
    modalities: modal('text', 'vision', 'image', 'audio', 'embedding'),
    capabilities: ['multi_provider'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    tags: ['marketplace', 'openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'openai/gpt-4o',
        provider_id: 'openrouter',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'anthropic/claude-sonnet-4',
        provider_id: 'openrouter',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'reasoning'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'google/gemini-2.5-pro',
        provider_id: 'openrouter',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['long_context', 'reasoning'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    base_url: 'https://api.groq.com',
    base_url_matchers: ['api.groq.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: { chat_completions: '/openai/v1/chat/completions' },
    auth_type: 'bearer',
    key_placeholder: 'gsk_...',
    modalities: modal('text'),
    capabilities: ['fast'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['llama', 'mixtral', 'gemma'],
    tags: ['fast', 'openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        provider_id: 'groq',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['fast'],
        limits: { max_context_tokens: 128000 },
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'llama-3.1-8b-instant',
        provider_id: 'groq',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['fast'],
        limits: { max_context_tokens: 128000 },
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    base_url: 'https://api.mistral.ai',
    base_url_matchers: ['api.mistral.ai'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
    },
    auth_type: 'bearer',
    key_placeholder: 'Bearer token...',
    modalities: modal('text', 'vision', 'embedding'),
    capabilities: ['coding', 'multilingual'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['mistral', 'codestral', 'pixtral'],
    tags: ['official', 'openai-compatible'],
    models: [
      {
        id: 'mistral-large-latest',
        provider_id: 'mistral',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'multilingual'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'pixtral-large-latest',
        provider_id: 'mistral',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['vision', 'multilingual'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'mistral-embed',
        provider_id: 'mistral',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: manualTokenPricing(null, 0),
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    base_url: 'https://api.deepseek.com',
    base_url_matchers: ['api.deepseek.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: { chat_completions: '/v1/chat/completions' },
    auth_type: 'bearer',
    key_placeholder: 'sk-...',
    modalities: modal('text'),
    capabilities: ['coding', 'reasoning', 'cost_effective'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['deepseek'],
    tags: ['openai-compatible'],
    models: [
      {
        id: 'deepseek-chat',
        provider_id: 'deepseek',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'cost_effective'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'deepseek-reasoner',
        provider_id: 'deepseek',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning', 'coding'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    base_url: 'https://api.x.ai',
    base_url_matchers: ['api.x.ai'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: { chat_completions: '/v1/chat/completions' },
    auth_type: 'bearer',
    key_placeholder: 'xai-...',
    modalities: modal('text', 'vision'),
    capabilities: ['reasoning', 'fast'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['grok'],
    tags: ['openai-compatible'],
    models: [
      {
        id: 'grok-3',
        provider_id: 'xai',
        modalities: modal('text', 'vision'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text', 'image'],
        output_types: ['text', 'json'],
        capabilities: ['reasoning'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'grok-3-mini',
        provider_id: 'xai',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['fast', 'reasoning'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    base_url: 'https://api.cohere.com',
    base_url_matchers: ['api.cohere.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v2/chat',
      embeddings: '/v2/embed',
      rerank: '/v2/rerank',
    },
    auth_type: 'bearer',
    key_placeholder: 'co-...',
    modalities: modal('text', 'embedding', 'rerank'),
    capabilities: ['rerank', 'embedding', 'multilingual'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['command', 'embed', 'rerank'],
    tags: ['official'],
    models: [
      {
        id: 'command-r-plus',
        provider_id: 'cohere',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['tool_use', 'rag'],
        pricing: manualTokenPricing(null, null),
        supports_streaming: true,
      },
      {
        id: 'embed-v4.0',
        provider_id: 'cohere',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text', 'image'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: manualTokenPricing(null, 0),
      },
      {
        id: 'rerank-v3.5',
        provider_id: 'cohere',
        modalities: modal('rerank'),
        endpoints: endpoints('rerank'),
        input_types: ['text', 'documents'],
        output_types: ['ranked_documents'],
        capabilities: ['rerank'],
        pricing: operatorPricing('1k_requests'),
        supports_rerank: true,
      },
    ],
  },
  {
    id: 'voyage',
    name: 'Voyage AI',
    base_url: 'https://api.voyageai.com',
    base_url_matchers: ['api.voyageai.com'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      embeddings: '/v1/embeddings',
      rerank: '/v1/rerank',
    },
    auth_type: 'bearer',
    key_placeholder: 'pa-...',
    modalities: modal('embedding', 'rerank'),
    capabilities: ['embedding', 'rerank'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['voyage', 'rerank'],
    tags: ['official'],
    models: [
      {
        id: 'voyage-3-large',
        provider_id: 'voyage',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: manualTokenPricing(null, 0),
      },
      {
        id: 'rerank-2',
        provider_id: 'voyage',
        modalities: modal('rerank'),
        endpoints: endpoints('rerank'),
        input_types: ['text', 'documents'],
        output_types: ['ranked_documents'],
        capabilities: ['rerank'],
        pricing: operatorPricing('1k_requests'),
        supports_rerank: true,
      },
    ],
  },
  {
    id: 'jina',
    name: 'Jina AI',
    base_url: 'https://api.jina.ai',
    base_url_matchers: ['api.jina.ai'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      embeddings: '/v1/embeddings',
      rerank: '/v1/rerank',
    },
    auth_type: 'bearer',
    key_placeholder: 'jina_...',
    modalities: modal('embedding', 'rerank'),
    capabilities: ['embedding', 'rerank', 'multilingual'],
    pricing: {
      source: 'manual_placeholder',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['jina'],
    tags: ['official'],
    models: [
      {
        id: 'jina-embeddings-v3',
        provider_id: 'jina',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding', 'multilingual'],
        pricing: manualTokenPricing(null, 0),
      },
      {
        id: 'jina-reranker-v2-base-multilingual',
        provider_id: 'jina',
        modalities: modal('rerank'),
        endpoints: endpoints('rerank'),
        input_types: ['text', 'documents'],
        output_types: ['ranked_documents'],
        capabilities: ['rerank', 'multilingual'],
        pricing: operatorPricing('1k_requests'),
        supports_rerank: true,
      },
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    base_url: 'https://api.together.xyz',
    base_url_matchers: ['api.together.xyz'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
      image_generations: '/v1/images/generations',
    },
    auth_type: 'bearer',
    key_placeholder: 'tgp_...',
    modalities: modal('text', 'vision', 'embedding', 'image'),
    capabilities: ['open_models', 'fast'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['meta-llama', 'Qwen', 'deepseek', 'BAAI'],
    tags: ['openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
        provider_id: 'together',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['open_models'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'BAAI/bge-large-en-v1.5',
        provider_id: 'together',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: operatorPricing(),
      },
      {
        id: 'black-forest-labs/FLUX.1-schnell',
        provider_id: 'together',
        modalities: modal('image'),
        endpoints: endpoints('image_generations'),
        input_types: ['text'],
        output_types: ['image'],
        capabilities: ['image_generation'],
        pricing: operatorPricing('image'),
      },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    base_url: 'https://api.fireworks.ai',
    base_url_matchers: ['api.fireworks.ai'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/inference/v1/chat/completions',
      embeddings: '/inference/v1/embeddings',
    },
    auth_type: 'bearer',
    key_placeholder: 'fw_...',
    modalities: modal('text', 'vision', 'embedding', 'image'),
    capabilities: ['open_models', 'fast'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['accounts/fireworks/models', 'llama', 'qwen'],
    tags: ['openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
        provider_id: 'fireworks',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['open_models'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'nomic-ai/nomic-embed-text-v1.5',
        provider_id: 'fireworks',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding'],
        pricing: operatorPricing(),
      },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    base_url: 'http://localhost:11434',
    base_url_matchers: ['localhost:11434', '127.0.0.1:11434'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
    },
    auth_type: 'none',
    key_placeholder: 'ollama (any value)',
    modalities: modal('text', 'vision', 'embedding'),
    capabilities: ['local', 'privacy'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    model_prefixes: ['llama', 'qwen', 'deepseek', 'mistral', 'nomic'],
    tags: ['local', 'openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'llama3.1',
        provider_id: 'ollama',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['local'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'qwen2.5-coder',
        provider_id: 'ollama',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['coding', 'local'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
      {
        id: 'nomic-embed-text',
        provider_id: 'ollama',
        modalities: modal('embedding'),
        endpoints: endpoints('embeddings'),
        input_types: ['text'],
        output_types: ['embedding'],
        capabilities: ['embedding', 'local'],
        pricing: operatorPricing(),
      },
    ],
  },
  {
    id: 'vllm',
    name: 'vLLM',
    base_url: 'http://localhost:8000',
    base_url_matchers: ['localhost:8000', '127.0.0.1:8000'],
    protocols: ['chat_completions'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      embeddings: '/v1/embeddings',
    },
    auth_type: 'bearer',
    key_placeholder: 'local token or any value',
    modalities: modal('text', 'vision', 'embedding'),
    capabilities: ['local', 'open_models'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    tags: ['local', 'openai-compatible'],
    allows_unknown_models: true,
    models: [
      {
        id: 'local-model',
        provider_id: 'vllm',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['local'],
        pricing: operatorPricing(),
        supports_streaming: true,
      },
    ],
  },
  {
    id: 'openai-compatible',
    name: 'OpenAI-Compatible Custom',
    base_url: 'https://YOUR_PROVIDER.example.com',
    base_url_matchers: [],
    protocols: ['chat_completions', 'responses'],
    default_protocol: 'chat_completions',
    endpoints: {
      chat_completions: '/v1/chat/completions',
      responses: '/v1/responses',
      embeddings: '/v1/embeddings',
      image_generations: '/v1/images/generations',
      image_edits: '/v1/images/edits',
      audio_transcriptions: '/v1/audio/transcriptions',
      audio_speech: '/v1/audio/speech',
      rerank: '/v1/rerank',
      realtime: '/v1/realtime',
    },
    auth_type: 'bearer',
    key_placeholder: 'provider key...',
    modalities: modal('text', 'vision', 'image', 'audio', 'video', 'embedding', 'rerank', 'realtime'),
    capabilities: ['custom', 'openai-compatible'],
    pricing: {
      source: 'operator_required',
      last_updated: PROVIDER_CATALOG_LAST_UPDATED,
      manual_review_required: true,
    },
    tags: ['custom', 'openai-compatible'],
    allows_unknown_models: true,
    manual_review_required: true,
    models: [
      {
        id: 'provider/model-id',
        provider_id: 'openai-compatible',
        modalities: modal('text'),
        endpoints: endpoints('chat_completions'),
        input_types: ['text'],
        output_types: ['text', 'json'],
        capabilities: ['custom'],
        pricing: operatorPricing(),
        manual_review_required: true,
        supports_streaming: true,
      },
    ],
  },
];
